
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - MODE=development
    ports:
      - "3001:80"
    networks:
      - test_default

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
    depends_on:
      - database 
    networks:
      - test_default

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_default

volumes:
  postgres_data:

networks:
  test_default: