entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: "websecure"
    #       scheme: "https"

  websecure:
    address: ":443"

accesslog: {}

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: true

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: "hanhtlc1410@gmail.com"
#       storage: "/certificates/acme.json"

#       httpChallenge:
#         entryPoint: "web"